server.port=8080
spring.application.name=cloudSaaS

# Supabase PostgreSQL - Session Pooler Configuration
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
spring.datasource.username=postgres.kdpaebdlspqevipivkql
spring.datasource.password=C8jvy7O88M1kvQS6
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT Configuration
jwt.secret=44aa045b56ded151e1373f58dc8f42ce70b2da6fca7775080934b018859aee56
jwt.expiration=86400000

# Mail Configuration - WalidSolutions SMTP (port 587, STARTTLS)
spring.mail.host=premium706.web-hosting.com
spring.mail.port=587
spring.mail.username=sindiboard@walidsolutions.com
spring.mail.password=*S!Nd!b0@rD*
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.ssl.enable=false
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.from=sindiboard@walidsolutions.com

# Superadmin Credentials
app.superadmin.email=walidcloud25@gmail.com
app.superadmin.password=S!Nd!b0@rD

# Azure Service Credential
azure.client-id=75192849-ca1a-4ae9-a999-0fc23165df2e
azure.tenant-id=dbfe07ed-9868-4c22-b0a2-b49a123d47ef
azure.client-secret=TMt8Q~9bKco6waInxOcR-uFNCIL-yaeDwPlNZc1F
azure.subscription-id=04540351-ef95-4772-8bed-1626650bf9ed

# Azure Billing Account/Profile Ids
azure.billing-account-id=2b9fe050-b841-5380-aee5-313ada68e707:f11b7aff-ce30-4b35-9fc6-766b182186b4_2019-05-31
azure.billing-profile-id=RCJI-H4QV-BG7-PGB

# Azure monitoring settings
azure.monitor.metrics-window-minutes=10
azure.cost.lookback-days=1