server.port=8080

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/cloudSaaSdb}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql

# JWT
jwt.secret=${jwt_secret}
jwt.expiration=2592000000


azure.workspace.ltrms=c5c3d2b7-80a9-43f7-a7e5-0a4ee528ad88
azure.workspace.pap=31c83c0e-5060-43ad-a8a4-68d816674f4b
azure.workspace.takwinland=80396b07-4761-4252-8459-9e1dbd2addf1
azure.workspace.cip=0ed1105d-90dc-4195-b6e0-179646efa3fe
# Super Admin
app.superadmin.email=${super_admin_email}
app.superadmin.password=${super_admin_password}

# smtp Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=znaidi2049@gmail.com
spring.mail.password=${smtp_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Azure Service Credential
azure.client-id=${azure_client_id}
azure.tenant-id=${azure_tenant_id}
azure.subscription-id=${azure_subscription_id}
azure.client-secret=${azure_client_secret}

# Azure Billing Account/Profile Ids
azure.billing-account-id=${azure_billing_account_id}
azure.billing-profile-id=${azure_billing_profile_id}

# Azure monitoring settings
azure.monitor.metrics-window-minutes=10
azure.cost.lookback-days=1

# OpenRouter Properties
openrouter.api.key=${ai_api_key}
openrouter.base.url=https://openrouter.ai/api/v1
openrouter.model.id=openrouter/auto
openrouter.max.tokens=20000
openrouter.temperature=0.5