server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/cloudSaaSdb
spring.datasource.username=znaidi
spring.datasource.password=12345678
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.path=/graphql

# JWT
jwt.secret=3f8b2c1d9e4a7f6b0c5d2e8a1f4b7c3d9e2a5f8b1c4d7e0a3f6b9c2d5e8a1f4
jwt.expiration=86400000

# Super Admin
app.superadmin.email=znaidi2049@gmail.com
app.superadmin.password=12345678

# smtp Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=znaidi2049@gmail.com
spring.mail.password=gawjerumjjxqqnaz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2ZWdhc3puYWlkaUBnbWFpbC5jb20iLCJyb2xlIjoiVEVDSE5JQ0FMIiwiaWF0IjoxNzc0MjkzMTYyLCJleHAiOjE3NzQzNzk1NjJ9.DmdDrZssJmemBuor8CIDEcLcsC3qVwTzMgxvmcZAaL4